### ISSUE TITLE
Compatibility with HA 2024.12.0

### ISSUE THREAD

**Issue by Hubert2208** [DeerMaximum/Technische-Alternative-CMI#104]
In Homeassistant 2024.12.0 the Component isn't starting

## Version of the custom_component
I use Version v1.9.4 

## Describe the bug
The Component isn't starting

## Debug log

Logger: homeassistant.setup
Quelle: setup.py:334
Erstmals aufgetreten: 5. Dezember 2024 um 19:17:42 (1 Vorkommnisse)
Zuletzt protokolliert: 5. Dezember 2024 um 19:17:42

Setup failed for custom integration 'ta_cmi': Unable to import component: No module named 'ta_cmi'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component
    self._component_future.result()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self._get_component, True
        ^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/ta_cmi/__init__.py", line 16, in <module>
    from ta_cmi import CMIAPI, ApiError, Device, InvalidCredentialsError, RateLimitError
ModuleNotFoundError: No module named 'ta_cmi'

**Comment by DeerMaximum** [comment]
It seems like the underlying library from the integration is not found. Normally Home Assistant should install it automatically. You could try to reinstall the integration (Remove the integration → restart → install → restart).

**Comment by Hubert2208** [comment]
seems to be a problem with HA running in a container. Reinstall does not change the behavior

**Comment by Hubert2208** [comment]
I found now a solution for the problem.
The Folder /config/deps/lib/python3.12/ have to be moved to /config/deps/lib/python3.13/
The new Version auf HA has bumped Python to Version 3.13
I also had an old folder /config/deps/lib/python3.11/. This one i deleted.

**Comment by DeerMaximum** [comment]
Great to hear that it is working now
