### ISSUE TITLE
Error during setup

### ISSUE THREAD

**Issue by Kime203** [DeerMaximum/Technische-Alternative-CMI#85]
## Description of the Bug
Hello, I am using V1.42.2 - B1.08 - H4.00 and I keep having the problem that the connection to the CMI cannot be established. From time to time it works but most of the time it does not. I have attached what I found in the log. I hope you can help me here.

## Debug log

```

2024-01-31 16:49:10.269 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: ta_cmi
2024-01-31 16:49:16.026 DEBUG (MainThread) [custom_components.ta_cmi] Finished fetching ta_cmi data in 296.387 seconds (success: True)
2024-01-31 16:49:16.026 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry C.M.I for ta_cmi
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 406, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ta_cmi/__init__.py", line 58, in async_setup_entry
await coordinator.async_config_entry_first_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_config_entry_first_refresh
await self._async_refresh(
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/ta_cmi/__init__.py", line 136, in _async_update_data
await asyncio.sleep(DEVICE_DELAY)
File "/usr/local/lib/python3.11/asyncio/tasks.py", line 649, in sleep
return await future
^^^^^^^^^^^^


```

**Comment by DeerMaximum** [comment]
Can you send me the debug logs with this configuration? This also activates the debug logs for the Python library used.
```yaml
logger:
  default: info
  logs:
    custom_components.ta_cmi: debug
    ta_cmi: debug
```

**Comment by Kime203** [comment]
Yes, I have set this up so where should I send the home-assistant.log?

**Comment by DeerMaximum** [comment]
That would be great

**Comment by Kime203** [comment]
Ok where should I send it? I don't want to publish the whole log here.

**Comment by DeerMaximum** [comment]
You can send them to this e-mail: home-assistant-logs.jcmup@simplelogin.com

**Comment by DeerMaximum** [comment]
Can you download the latest beta version (1.9.1-dev) and see if the error still exists?

**Comment by Kime203** [comment]
Hello, I did it and it should work now
